baseurl = "https://trevordjones.github.io/cheatsheets/"
languageCode = "en-us"
title = "Rails Development"
Paginate = 10

[params]
  githubName = "trevordjones"
  description = "Common Commands"
  hideShareOptions = true
